# Lab 2: ML Life Cycle: Data Understanding and Data Preparation

In [4]:
import os
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns

In this lab, you will practice the second and third steps of the machine learning life cycle: data understanding and data preparation. You will beging preparing your data so that it can be used to train a machine learning model that solves a regression problem. Note that by the end of the lab, your data set won't be completely ready for the modeling phase, but you will gain experience using some common data preparation techniques. 

You will complete the following tasks to transform your data:

1. Build your data matrix and define your ML problem:
    * Load the Airbnb "listings" data set into a DataFrame and inspect the data
    * Define the label and convert the label's data type to one that is more suitable for modeling
    * Identify features
2. Clean your data:
    * Handle outliers by building a new regression label column by winsorizing outliers
    * Handle missing data by replacing all missing values in the dataset with means
3. Perform feature transformation using one-hot encoding
4. Explore your data:
    * Identify two features with the highest correlation with label
    * Build appropriate bivariate plots to visualize the correlations between features and the label
5. Analysis:
    * Analyze the relationship between the features and the label
    * Brainstorm what else needs to be done to fully prepare the data for modeling

## Part 1. Build Your Data Matrix (DataFrame) and Define Your ML Problem

#### Load a Data Set and Save it as a Pandas DataFrame

We will be working with the Airbnb NYC "listings" data set. Use the specified path and name of the file to load the data. Save it as a Pandas DataFrame called `df`.

In [5]:
# Do not remove or edit the line below:
filename = os.path.join(os.getcwd(), "data", "airbnbData.csv")

**Task**: Load the data and save it to DataFrame `df`.

<i>Note:</i> You may receive a warning message. Ignore this warning.

In [6]:
df = pd.read_csv(filename)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (67) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,https://www.airbnb.com/rooms/2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,...,4.79,4.86,4.41,NaN,f,3,3,0,0,0.33
1,3831,https://www.airbnb.com/rooms/3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,https://a0.muscache.com/pictures/e49999c2-9fd5...,4869,https://www.airbnb.com/users/show/4869,...,4.80,4.71,4.64,NaN,f,1,1,0,0,4.86
2,5121,https://www.airbnb.com/rooms/5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.52
3,5136,https://www.airbnb.com/rooms/5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,...,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
4,5178,https://www.airbnb.com/rooms/5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,...,4.42,4.87,4.36,NaN,f,1,0,1,0,3.68

####  Inspect the Data

<b>Task</b>: Display the shape of `df` -- that is, the number of rows and columns.

In [7]:
df_shape = df.shape
print("The shape of the DataFrame is:", df_shape)

The shape of the DataFrame is: (38277, 74)

<b>Task</b>: Display the column names.

In [8]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

**Task**: Get a peek at the data by displaying the first few rows, as you usually do.

In [9]:
df.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,https://www.airbnb.com/rooms/2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,...,4.79,4.86,4.41,NaN,f,3,3,0,0,0.33
1,3831,https://www.airbnb.com/rooms/3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,https://a0.muscache.com/pictures/e49999c2-9fd5...,4869,https://www.airbnb.com/users/show/4869,...,4.80,4.71,4.64,NaN,f,1,1,0,0,4.86
2,5121,https://www.airbnb.com/rooms/5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.52
3,5136,https://www.airbnb.com/rooms/5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,...,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
4,5178,https://www.airbnb.com/rooms/5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,...,4.42,4.87,4.36,NaN,f,1,0,1,0,3.68

#### Define the Label

Assume that your goal is to train a machine learning model that predicts the price of an Airbnb. This is an example of supervised learning and is a regression problem. In our dataset, our label will be the `price` column. Let's inspect the values in the `price` column.

In [10]:
df['price']

0        $150.00
1         $75.00
2         $60.00
3        $275.00
4         $68.00
          ...
38272     $79.00
38273     $76.00
38274    $116.00
38275    $106.00
38276    $689.00
Name: price, Length: 38277, dtype: object

Notice the `price` column contains values that are listed as $<$currency_name$>$$<$numeric_value$>$. 
<br>For example, it contains values that look like this: `$120`. <br>

**Task**:  Obtain the data type of the values in this column:

In [11]:
price_column_dtype = df['price'].dtype
price_column_dtype

dtype('O')

Notice that the data type is "object," which in Pandas translates to the String data type.

**Task**:  Display the first 15 unique values of  the `price` column:

In [12]:
unique_price = df['price'].unique()[:15]
unique_price

array(['$150.00', '$75.00', '$60.00', '$275.00', '$68.00', '$98.00',
       '$89.00', '$65.00', '$62.00', '$90.00', '$199.00', '$96.00',
       '$299.00', '$140.00', '$175.00'], dtype=object)

In order for us to use the prices for modeling, we will have to transform the values in the `price` column from strings to floats. We will:

* remove the dollar signs (in this case, the platform forces the currency to be the USD, so we do not need to worry about targeting, say, the Japanese Yen sign, nor about converting the values into USD). 
* remove the commas from all values that are in the thousands or above: for example, `$2,500`. 

The code cell below accomplishes this.

In [13]:
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].astype(float)

**Task**:  Display the first 15 unique values of  the `price` column again to make sure they have been transformed.

In [14]:
unique_prices2 = df['price'].unique()[:15]
unique_prices2

array([150.,  75.,  60., 275.,  68.,  98.,  89.,  65.,  62.,  90., 199.,
        96., 299., 140., 175.])

#### Identify Features

Simply by inspecting the data, let's identify some columns that should not serve as features - those that will not help us solve our predictive ML problem.

Some that stand out are columns that contain website addresses (URLs).

**Task**: Create a list which contains the names of columns that contain URLs. Save the resulting list to variable `url_colnames`.

*Tip*: There are different ways to accomplish this, including using Python list comprehensions.

In [15]:
url_colnames = [col for col in df.columns if 'url' in col.lower()]
url_colnames

['listing_url',
 'picture_url',
 'host_url',
 'host_thumbnail_url',
 'host_picture_url']

**Task**: Drop the columns with the specified names contained in list `url_colnames` in place (that is, make sure this change applies to the original DataFrame `df`, instead of creating a temporary new DataFrame object with fewer columns).

In [16]:
df.drop(columns=url_colnames, inplace=True)
df.head()

,id,scrape_id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,2845,Jennifer,2008-09-09,"New York, New York, United States",...,4.79,4.86,4.41,NaN,f,3,3,0,0,0.33
1,3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",...,4.80,4.71,4.64,NaN,f,1,1,0,0,4.86
2,5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,7356,Garon,2009-02-03,"New York, New York, United States",...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.52
3,5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,7378,Rebecca,2009-02-03,"Brooklyn, New York, United States",...,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
4,5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",8967,Shunichi,2009-03-03,"New York, New York, United States",...,4.42,4.87,4.36,NaN,f,1,0,1,0,3.68

**Task**: Display the shape of the data to verify that the new number of columns is what you expected.

In [17]:
df_shape_after_dropping = df.shape
df_shape_after_dropping

(38277, 69)

**Task**: In the code cell below, display the features that we will use to solve our ML problem.

In [18]:
remaining_features = df.columns
features = [col for col in remaining_features if col != 'price']
features

['id',
 'scrape_id',
 'last_scraped',
 'name',
 'description',
 'neighborhood_overview',
 'host_id',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

**Task**: Are there any other features that you think may not be well suited for our machine learning problem? Note your findings in the markdown cell below.

Some features that may not be well suited for this ML problem could be:
any features with id in them
features with min and max

## Part 2. Clean Your Data

Let's now handle outliers and missing data.

### a. Handle Outliers

Let us prepare the data in our label column. Namely, we will detect and replace outliers in the data using winsorization.

**Task**: Create a new version of the `price` column, named `label_price`, in which you will replace the top and bottom 1% outlier values with the corresponding percentile value. Add this new column to the DataFrame `df`.

Remember, you will first need to load the `stats` module from the `scipy` package:

In [19]:
from scipy.stats import mstats
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)
df['label_price'] = mstats.winsorize(df['price'], limits=[0.01, 0.01])
print(df[['price', 'label_price']].head())

   price  label_price
0  150.0        150.0
1   75.0         75.0
2   60.0         60.0
3  275.0        275.0
4   68.0         68.0

Let's verify that the new column `label_price` was added to DataFrame `df`:

In [20]:
df.head()

,id,scrape_id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,label_price
0,2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,2845,Jennifer,2008-09-09,"New York, New York, United States",...,4.86,4.41,NaN,f,3,3,0,0,0.33,150.0
1,3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",...,4.71,4.64,NaN,f,1,1,0,0,4.86,75.0
2,5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,7356,Garon,2009-02-03,"New York, New York, United States",...,4.47,4.52,NaN,f,2,0,2,0,0.52,60.0
3,5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,7378,Rebecca,2009-02-03,"Brooklyn, New York, United States",...,4.50,5.00,NaN,f,1,1,0,0,0.02,275.0
4,5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",8967,Shunichi,2009-03-03,"New York, New York, United States",...,4.87,4.36,NaN,f,1,0,1,0,3.68,68.0

**Task**: Check that the values of `price` and `label_price` are *not* identical. 

You will do this by subtracting the two columns and finding the resulting *unique values*  of the resulting difference. <br>Note: If all values are identical, the difference would not contain unique values. If this is the case, outlier removal did not work.

In [21]:
difference = df['price'] - df['label_price']
unique_differences = difference.unique()
unique_differences

array([ 0.000e+00,  1.500e+03,  3.000e+02,  1.000e+03,  1.979e+03,
       -1.000e+00,  8.990e+02,  2.000e+02,  9.990e+02,  5.000e+02,
       -8.000e+00,  5.000e+03,  4.250e+03,  5.500e+02,  2.500e+02,
        5.500e+03,  1.750e+03,  2.750e+03,  6.000e+02, -1.100e+01,
        1.249e+03,  4.330e+02,  5.700e+01,  3.930e+02, -4.000e+00,
        4.000e+02,  1.695e+03,  8.990e+03,  2.140e+02, -1.400e+01,
        8.999e+03,  7.630e+02, -2.000e+00, -9.000e+00,  2.430e+02,
        1.000e+02,  6.400e+01,  2.974e+03,  7.700e+01, -3.000e+00,
       -7.000e+00,  3.500e+02,  2.450e+02,  8.100e+01,  5.710e+02,
        6.314e+03, -5.000e+00, -1.000e+01,  2.000e+00,  9.900e+01,
        1.200e+03,  4.300e+02,  1.100e+03,  8.500e+01,  4.000e+03,
        9.000e+03,  1.350e+03,  5.000e+01,  2.000e+03,  1.299e+03,
        1.430e+02,  1.499e+03,  3.700e+02, -1.900e+01,  6.184e+03,
       -1.300e+01,  2.210e+02,  1.857e+03, -1.500e+01,  9.000e+02,
        7.500e+01, -6.000e+00,  6.430e+02,  3.929e+03,  2.910e+02,
        3.990e+02,  8.000e+03,  5.429e+03,  3.000e+03, -1.800e+01,
        5.143e+03,  1.400e+03,  4.750e+02,  2.214e+03,  1.910e+02,
        4.250e+02,  1.250e+02,  3.330e+02,  4.990e+02,  8.000e+02,
        2.250e+02,  2.500e+03,  8.190e+02,  6.000e+03,  3.030e+02,
        3.070e+02,  1.640e+02,  3.420e+02,  5.600e+01,  2.600e+03,
        2.200e+03,  5.700e+02,  1.642e+03,  7.000e+00,  9.810e+02,
        2.120e+02,  1.850e+03,  4.500e+01,  4.510e+02,  5.120e+02,
        2.360e+02,  6.200e+01,  1.020e+02,  2.590e+02,  7.500e+02,
        9.750e+02,  5.290e+02,  2.960e+02,  9.500e+02,  1.600e+03,
        2.750e+02,  4.640e+02,  2.570e+02, -2.900e+01, -1.700e+01,
        9.500e+01,  2.850e+02,  3.382e+03,  1.839e+03,  1.261e+03,
        2.900e+01,  2.260e+02,  1.130e+02,  9.000e+00,  2.160e+02,
        1.160e+02, -1.200e+01,  4.950e+02,  2.500e+01,  2.860e+02,
        2.557e+03,  1.614e+03,  7.100e+01,  5.400e+01,  5.750e+02,
        1.700e+03,  2.400e+01,  1.700e+01,  1.140e+02,  2.900e+02,
        2.990e+02,  9.950e+02,  1.760e+02,  8.300e+02,  2.520e+03,
        8.650e+02,  6.700e+01,  1.797e+03,  2.729e+03,  7.600e+02,
        1.640e+03,  6.860e+02,  2.490e+02,  3.730e+02,  5.500e+01,
        7.420e+02,  2.920e+02,  1.436e+03,  3.860e+02,  3.570e+02,
        4.740e+02,  2.333e+03,  1.100e+01,  1.400e+01,  3.143e+03,
        4.500e+02,  8.300e+01,  1.990e+02,  8.560e+02,  1.370e+02,
        7.600e+01,  1.290e+02,  6.540e+02,  3.400e+01,  3.690e+02,
        8.170e+02,  4.790e+02,  8.970e+02,  3.140e+02,  3.320e+02,
        2.820e+02,  1.090e+02,  1.260e+02,  1.490e+02,  2.110e+02,
        1.232e+03,  3.464e+03,  2.119e+03,  3.310e+02,  5.650e+02,
        1.071e+03,  2.855e+03,  1.050e+03,  1.157e+03,  4.655e+03,
        9.800e+02])

### b. Handle Missing Data

Next we are going to find missing values in our entire dataset and impute the missing values by
replace them with means.

#### Identifying missingness

**Task**: Check if a given value in the data is missing, and sum up the resulting values by columns. Save this sum to variable `nan_count`. Print the results.

In [22]:
nan_count = df.isna().sum()
nan_count

id                                                 0
scrape_id                                          0
last_scraped                                       0
name                                              13
description                                     1192
                                                ...
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               9504
label_price                                        0
Length: 70, dtype: int64

Those are more columns than we can eyeball! For this exercise, we don't care about the number of missing values -- we just want to get a list of columns that have *any* missing values.

<b>Task</b>: From the variable `nan_count`, create a new series called `nan_detected` that contains `True` or `False` values that indicate whether the number of missing values is *not zero*:

In [23]:
nan_detected = nan_count > 0
nan_detected

id                                              False
scrape_id                                       False
last_scraped                                    False
name                                             True
description                                      True
                                                ...
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                                True
label_price                                     False
Length: 70, dtype: bool

Since replacing the missing values with the mean only makes sense for the columns that contain numerical values (and not for strings), let us create another condition: the *type* of the column must be `int` or `float`.

**Task**: Create a series that contains `True` if the type of the column is either `int64` or `float64`. Save the results to the variable `is_int_or_float`.

In [24]:
is_int_or_float = df.dtypes.isin([np.int64, np.float64])
is_int_or_float

id                                              False
scrape_id                                       False
last_scraped                                    False
name                                            False
description                                     False
                                                ...
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                               False
label_price                                     False
Length: 70, dtype: bool

<b>Task</b>: Combine the two binary series (`nan_detected` and `is_int_or_float`) into a new series named `to_impute`. It will contain the value `True` if a column contains missing values *and* is of type 'int' or 'float'

In [25]:
to_impute = nan_detected & is_int_or_float
to_impute

id                                              False
scrape_id                                       False
last_scraped                                    False
name                                            False
description                                     False
                                                ...
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                               False
label_price                                     False
Length: 70, dtype: bool

Finally, let's display a list that contains just the selected column names contained in `to_impute`:

In [26]:
df.columns[to_impute]

Index([], dtype='object')

We just identified and displayed the list of candidate columns for potentially replacing missing values with the column mean.

Assume that you have decided that you should impute the values for these specific columns: `host_listings_count`, `host_total_listings_count`, `bathrooms`, `bedrooms`, and `beds`:

In [27]:
to_impute_selected = ['host_listings_count', 'host_total_listings_count', 'bathrooms',
       'bedrooms', 'beds']

#### Keeping record of the missingness: creating dummy variables

As a first step, you will now create dummy variables indicating the missingness of the values.

**Task**: For every column listed in `to_impute_selected`, create a new corresponding column called `<original-column-name>_na`. These columns should contain the a `True`or `False` value in place of `NaN`.

In [28]:
for column in to_impute_selected: df[f'{column}_na'] = df[column].isna()

Check that the DataFrame contains the new variables:

In [29]:
df.head()

,id,scrape_id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,label_price,host_listings_count_na,host_total_listings_count_na,bathrooms_na,bedrooms_na,beds_na
0,2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,2845,Jennifer,2008-09-09,"New York, New York, United States",...,3,0,0,0.33,150.0,False,False,True,True,False
1,3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",...,1,0,0,4.86,75.0,False,False,True,False,False
2,5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,7356,Garon,2009-02-03,"New York, New York, United States",...,0,2,0,0.52,60.0,False,False,True,False,False
3,5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,7378,Rebecca,2009-02-03,"Brooklyn, New York, United States",...,1,0,0,0.02,275.0,False,False,True,False,False
4,5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",8967,Shunichi,2009-03-03,"New York, New York, United States",...,0,1,0,3.68,68.0,False,False,True,False,False

#### Replacing the missing values with mean values of the column

**Task**: For every column listed in `to_impute_selected`, fill the missing values with the corresponding mean of all values in the column (do not create new columns).

In [30]:
for column in to_impute_selected: 
    mean_value = df[column].mean()
    df[column].fillna(mean_value, inplace=True)

Check your results below. The code displays the count of missing values for each of the selected columns.

In [31]:
for colname in to_impute_selected:
    print("{} missing values count :{}".format(colname, np.sum(df[colname].isnull(), axis = 0)))

host_listings_count missing values count :0
host_total_listings_count missing values count :0
bathrooms missing values count :38277
bedrooms missing values count :0
beds missing values count :0

Why did the `bathrooms` column retain missing values after our imputation?

**Task**: List the unique values of the `bathrooms` column.

In [32]:
unique_bathrooms = df['bathrooms'].unique()
unique_bathrooms

array([nan])

The column did not contain a single value (except the `NaN` indicator) to begin with.

## Part 3. Perform One-Hot Encoding

Machine learning algorithms operate on numerical inputs. Therefore, we have to transform text data into some form of numerical representation to prepare our data for the model training phase. Some features that contain text data are categorical. Others are not. For example, we removed all of the features that contained URLs. These features were not categorical, but rather contained what is called unstructured text. However, not all features that contain unstructured text should be removed, as they can contain useful information for our machine learning problem. Unstructured text data is usually handled by Natural Language Processing (NLP) techniques. You will learn more about NLP later in this course. 

However, for features that contain categorical values, one-hot encoding is a common feature engineering technique that transforms them into binary representations.

We will first choose one feature column to one-hot encode: `host_response_time`. Let's inspect the unique values this feature can have.

In [33]:
df['host_response_time'].unique()

array(['within a day', 'a few days or more', 'within an hour', nan,
       'within a few hours'], dtype=object)

Note that each entry can contain one of five possible values. 

**Task**: Since one of these values is `NaN`, replace every entry in the column `host_response_time` that contains a `NaN` value with the string 'unavailable'.

In [34]:
df['host_response_time'].fillna('unavailable', inplace=True)
print(df['host_response_time'].unique())

['within a day' 'a few days or more' 'within an hour' 'unavailable'
 'within a few hours']

Let's inspect the `host_response_time` column to see the new values.

In [35]:
df['host_response_time'].unique()

array(['within a day', 'a few days or more', 'within an hour',
       'unavailable', 'within a few hours'], dtype=object)

**Task**: Use `pd.get_dummies()` to one-hot encode the `host_response_time` column. Save the result to DataFrame `df_host_response_time`.

In [36]:
df_host_response_time = pd.get_dummies(df['host_response_time'], prefix='host_response_time')
df_host_response_time

,host_response_time_a few days or more,host_response_time_unavailable,host_response_time_within a day,host_response_time_within a few hours,host_response_time_within an hour
0,0,0,1,0,0
1,1,0,0,0,0
2,0,0,0,0,1
3,0,0,1,0,0
4,0,0,1,0,0
...,...,...,...,...,...
38272,0,0,0,1,0
38273,0,0,0,1,0
38274,0,0,0,0,1
38275,0,0,0,0,1
38276,0,0,0,0,1

**Task**: Since the `pd.get_dummies()` function returned a new DataFrame rather than making the changes to the original DataFrame `df`, add the new DataFrame `df_host_response_time` to DataFrame `df`, and delete the original `host_response_time` column from DataFrame `df`.

In [37]:
df = pd.concat([df, df_host_response_time], axis=1)
df.drop(columns=['host_response_time'], inplace=True)

Let's inspect DataFrame `df` to see the changes that have been made.

In [38]:
df.columns

Index(['id', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'host_id', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'label_price', 'host_listings_count_na', 'host_total_listings_count_na',
       'bathrooms_na', 'bedrooms_na', 'beds_na',
       'host_response_time_a few days or more',
       'host_response_time_unavailable', 'host_response_time_within a day',
       'host_response_time_within a few hours',
       'host_response_time_within an hour'],
      dtype='object')

#### One-hot encode additional features

**Task**: Use the code cell below to find columns that contain string values  (the 'object' data type) and inspect the *number* of unique values each column has.

In [39]:
string_columns = df.select_dtypes(include=['object'])
unique_counts = string_columns.nunique()
unique_counts

last_scraped                        2
name                            36870
description                     34133
neighborhood_overview           18616
host_name                        9123
host_since                       4289
host_location                    1747
host_about                      14424
host_response_rate                 88
host_acceptance_rate              101
host_is_superhost                   2
host_neighbourhood                484
host_verifications                526
host_has_profile_pic                2
host_identity_verified              2
neighbourhood                     207
neighbourhood_cleansed            222
neighbourhood_group_cleansed        5
property_type                      78
room_type                           4
bathrooms_text                     30
amenities                       31740
has_availability                    2
calendar_last_scraped               2
first_review                     3171
last_review                      2560
license                             1
instant_bookable                    2
dtype: int64

**Task**: Based on your findings, identify features that you think should be transformed using one-hot encoding.

1. Use the code cell below to inspect the unique *values* that each of these features have.

In [40]:
features_to_encode = [
    'neighbourhood_group_cleansed', 
    'room_type', 
    'host_is_superhost', 
    'host_has_profile_pic', 
    'host_identity_verified', 
    'instant_bookable'
]
for feature in features_to_encode:
    print(f"Unique values in '{feature}':")
    print(df[feature].unique())
    print()

Unique values in 'neighbourhood_group_cleansed':
['Manhattan' 'Brooklyn' 'Queens' 'Staten Island' 'Bronx']

Unique values in 'room_type':
['Entire home/apt' 'Private room' 'Hotel room' 'Shared room']

Unique values in 'host_is_superhost':
['f' 't' nan]

Unique values in 'host_has_profile_pic':
['t' 'f' nan]

Unique values in 'host_identity_verified':
['t' 'f' nan]

Unique values in 'instant_bookable':
['f' 't']

2.  List these features and explain why they would be suitable for one-hot encoding. Note your findings in the markdown cell below.

neighbourhood_group_cleansed - different areas ('Manhattan', 'Brooklyn', etc.), one-hot encoding helps the model understand locations.

room_type - types of rooms ('Entire home/apt', 'Private room', etc.), ne-hot encoding makes it easy for the model to tell them apart.

host_is_superhost - whether the host is a superhost ('f', 't'), one-hot encoding converts this to a simple yes/no format.

host_has_profile_pic - if the host has a profile picture ('t', 'f'), one-hot encoding turns this into a yes/no format.

host_identity_verified - whether the host's identity is verified ('t', 'f'), one-hot encoding makes it a clear yes/no.

instant_bookable - if the listing is instantly bookable ('f', 't'), one-hot encoding makes it yes/no.

**Task**: In the code cell below, one-hot encode one of the features you have identified and replace the original column in DataFrame `df` with the new one-hot encoded columns.

In [41]:
import pandas as pd
df_encoded = pd.get_dummies(df, columns=['neighbourhood_group_cleansed'], prefix='neighbourhood')
df_encoded.head()

,id,scrape_id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,host_response_time_a few days or more,host_response_time_unavailable,host_response_time_within a day,host_response_time_within a few hours,host_response_time_within an hour,neighbourhood_Bronx,neighbourhood_Brooklyn,neighbourhood_Manhattan,neighbourhood_Queens,neighbourhood_Staten Island
0,2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,2845,Jennifer,2008-09-09,"New York, New York, United States",...,0,0,1,0,0,0,0,1,0,0
1,3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",...,1,0,0,0,0,0,1,0,0,0
2,5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,7356,Garon,2009-02-03,"New York, New York, United States",...,0,0,0,0,1,0,1,0,0,0
3,5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,7378,Rebecca,2009-02-03,"Brooklyn, New York, United States",...,0,0,1,0,0,0,1,0,0,0
4,5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",8967,Shunichi,2009-03-03,"New York, New York, United States",...,0,0,1,0,0,0,0,1,0,0

## Part 4. Explore Your Data

You will now perform exploratory data analysis in preparation for selecting your features as part of feature engineering. 

#### Identify Correlations

We will focus on identifying which features in the data have the highest correlation with the label.

Let's first run the `corr()` method on DataFrame `df` and save the result to the variable `corr_matrix`. Let's round the resulting correlations to five decimal places:

In [42]:
corr_matrix = round(df.corr(),5)
corr_matrix

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,host_listings_count_na,host_total_listings_count_na,bathrooms_na,bedrooms_na,beds_na,host_response_time_a few days or more,host_response_time_unavailable,host_response_time_within a day,host_response_time_within a few hours,host_response_time_within an hour
id,1.00000,-0.0,0.58617,0.12986,0.12986,0.01000,0.08708,0.03540,NaN,0.04503,...,-0.00830,-0.00830,NaN,0.03343,0.13640,0.01215,-0.35410,-0.01164,0.12780,0.29187
scrape_id,-0.00000,1.0,0.00000,-0.00000,-0.00000,0.00000,-0.00000,0.00000,NaN,0.00000,...,-0.00000,-0.00000,NaN,0.00000,-0.00000,0.00000,-0.00000,-0.00000,-0.00000,-0.00000
host_id,0.58617,0.0,1.00000,0.03189,0.03189,0.04148,0.11620,0.02723,NaN,0.02202,...,-0.00371,-0.00371,NaN,0.03354,0.09218,0.04055,-0.24094,-0.05562,0.01844,0.26491
host_listings_count,0.12986,-0.0,0.03189,1.00000,1.00000,0.03475,-0.08843,-0.02621,NaN,-0.01710,...,-0.00000,-0.00000,NaN,0.01297,-0.01032,-0.03124,-0.11686,-0.03119,-0.01468,0.17132
host_total_listings_count,0.12986,-0.0,0.03189,1.00000,1.00000,0.03475,-0.08843,-0.02621,NaN,-0.01710,...,-0.00000,-0.00000,NaN,0.01297,-0.01032,-0.03124,-0.11686,-0.03119,-0.01468,0.17132
latitude,0.01000,0.0,0.04148,0.03475,0.03475,1.00000,0.05718,-0.04745,NaN,-0.07150,...,0.00199,0.00199,NaN,0.05533,0.02258,0.02052,0.01134,0.01410,-0.00499,-0.02598
longitude,0.08708,-0.0,0.11620,-0.08843,-0.08843,0.05718,1.00000,0.00374,NaN,0.00752,...,-0.01261,-0.01261,NaN,-0.10992,0.00221,-0.01400,-0.07471,-0.03805,0.03534,0.08358
accommodates,0.03540,0.0,0.02723,-0.02621,-0.02621,-0.04745,0.00374,1.00000,NaN,0.70586,...,0.00519,0.00519,NaN,-0.05957,-0.06916,0.01101,-0.11168,0.01642,-0.00382,0.11060
bathrooms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bedrooms,0.04503,0.0,0.02202,-0.01710,-0.01710,-0.07150,0.00752,0.70586,NaN,1.00000,...,-0.00089,-0.00089,NaN,-0.00000,-0.04571,0.01969,-0.09343,0.03512,0.01114,0.06432
beds,0.03289,0.0,0.03689,-0.03151,-0.03151,-0.05388,0.03136,0.73665,NaN,0.72914,...,0.00741,0.00741,NaN,-0.08783,0.00000,0.02056,-0.10810,0.01886,0.00242,0.09628
price,0.04256,-0.0,0.02907,0.07492,0.07492,0.02734,-0.11484,0.30803,NaN,0.25383,...,0.02149,0.02149,NaN,0.00598,-0.01596,0.02432,-0.05266,-0.00026,-0.01433,0.05805
minimum_nights,-0.12067,0.0,-0.10640,0.19739,0.19739,0.03422,-0.08550,-0.08474,NaN,-0.02749,...,-0.00772,-0.00772,NaN,0.01476,-0.01830,0.03087,0.18254,-0.00695,0.00592,-0.21377
maximum_nights,-0.00696,0.0,-0.00385,-0.00080,-0.00080,0.00561,-0.00296,-0.00494,NaN,0.00002,...,-0.00016,-0.00016,NaN,0.01498,-0.00135,-0.00108,0.00577,-0.00153,-0.00210,-0.00334
minimum_minimum_nights,-0.10234,0.0,-0.09188,0.26125,0.26125,0.03317,-0.08397,-0.07485,NaN,-0.02546,...,-0.00685,-0.00685,NaN,0.01191,-0.01823,0.02434,0.15024,-0.01002,-0.00678,-0.16408
maximum_minimum_nights,-0.00041,-0.0,-0.04521,0.65300,0.65300,0.04352,-0.09520,-0.05134,NaN,-0.01708,...,-0.00582,-0.00582,NaN,0.03254,-0.02851,-0.00457,0.00076,-0.02714,-0.02551,0.03672
minimum_maximum_nights,0.00747,-0.0,0.02572,-0.00349,-0.00349,0.01735,-0.00780,-0.00249,NaN,-0.01161,...,-0.00078,-0.00078,NaN,-0.00228,-0.00673,-0.00543,-0.00942,0.02956,-0.01049,0.00315
maximum_maximum_nights,0.01461,0.0,0.04267,-0.00529,-0.00529,0.01598,-0.01993,-0.00931,NaN,-0.01705,...,-0.00121,-0.00121,NaN,-0.00956,-0.00781,-0.00845,-0.02371,0.02398,-0.01634,0.02789
minimum_nights_avg_ntm,-0.00338,-0.0,-0.04707,0.65239,0.65239,0.04379,-0.09507,-0.05266,NaN,-0.01782,...,-0.00579,-0.00579,NaN,0.03210,-0.02848,-0.00364,0.00547,-0.02691,-0.02692,0.03209
maximum_nights_avg_ntm,0.01149,0.0,0.03438,-0.00451,-0.00451,0.01828,-0.01401,-0.00558,NaN,-0.01465,...,-0.00103,-0.00103,NaN,-0.00605,-0.00831,-0.00717,-0.01380,0.02215,-0.01386,0.01568
calendar_updated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
availability_30,0.25190,-0.0,0.26850,0.07148,0.07148,0.00261,0.13025,0.04429,NaN,0.01816,...,-0.01863,-0.01863,NaN,-0.01414,0.09611,0.20254,-0.29428,0.04232,0.10312,0.12962
availability_60,0.32793,-0.0,0.32728,0.06218,0.06218,0.00026,0.15062,0.07983,NaN,0.04432,...,-0.00954,-0.00954,NaN,-0.00904,0.09098,0.18352,-0.43295,0.05946,0.13745,0.25344
availability_90,0.34401,-0.0,0.33395,0.06279,0.06279,-0.00157,0.14953,0.09096,NaN,0.05567,...,-0.00605,-0.00605,NaN,-0.00320,0.09143,0.17710,-0.47929,0.08130,0.14265,0.29008
availability_365,0.28722,0.0,0.27332,0.14287,0.14287,0.01383,0.09596,0.10293,NaN,0.08280,...,0.00180,0.00180,NaN,0.00587,0.08961,0.12545,-0.47520,0.10797,0.17218,0.26996
number_of_reviews,-0.29164,0.0,-0.12215,-0.06617,-0.06617,-0.04801,0.06759,0.07255,NaN,0.00408,...,0.00083,0.00083,NaN,-0.02606,-0.05311,-0.03115,-0.16121,0.00818,-0.00846,0.19174
number_of_reviews_ltm,0.07737,0.0,0.11469,-0.04448,-0.04448,-0.04884,0.06458,0.08118,NaN,0.02836,...,-0.00502,-0.00502,NaN,0.01208,-0.03291,-0.06060,-0.22794,-0.03950,-0.02346,0.31743
number_of_reviews_l30d,0.15257,-0.0,0.15333,-0.04962,-0.04962,-0.04339,0.07309,0.08552,NaN,0.03271,...,-0.00669,-0.00669,NaN,-0.00913,-0.01860,-0.07216,-0.24822,-0.05445,-0.02925,0.35797
review_scores_rating,0.01187,0.0,-0.04397,-0.00742,-0.00742,-0.03767,0.00523,0.03097,NaN,0.01686,...,-0.02457,-0.02457,NaN,-0.00793,-0.01925,-0.06101,-0.09901,0.02862,0.02229,0.09629
review_scores_accuracy,-0.08867,0.0,-0.15428,-0.02365,-0.02365,-0.04076,-0.01136,-0.00422,NaN,-0.00323,...,-0.01079,-0.01079,NaN,-0.01799,-0.04077,-0.07606,0.04080,0.00761,-0.04651,0.01555
review_scores_cleanliness,0.00424,0.0,-0.05183,-0.00694,-0.00694,-0.03469,0.00772,0.03702,NaN,0.03206,...,0.00688,0.00688,NaN,0.00085,-0.03027,-0.06482,-0.06196,0.01355,-0.01300,0.09180
review_scores_checkin,-0.09156,0.0,-0.14890,-0.01701,-0.01701,-0.04612,-0.00525,-0.00125,NaN,0.00638,...,-0.00272,-0.00272,NaN,-0.02634,-0.04050,-0.08196,0.02230,0.01290,-0.01974,0.01498
review_scores_communication,-0.11950,0.0,-0.17420,-0.05032,-0.05032,-0.04250,-0.01358,-0.00067,NaN,-0.00019,...,-0.01654,-0.01654,NaN,-0.03450,-0.03904,-0.08031,0.05199,-0.00556,-0.04243,0.01028
review_scores_location,0.00322,0.0,-0.07864,0.00638,0.00638,0.01355,-0.13822,-0.01220,NaN,-0.01053,...,0.00638,0.00638,NaN,0.03420,-0.02043,-0.04102,0.01118,0.00999,-0.01360,0.00806
review_scores_value,-0.07080,0.0,-0.13340,-0.07391,-0.07391,-0.04887,0.00052,-0.00778,NaN,0.00074,...,-0.01150,-0.01150,NaN,-0.04448,-0.03429,-0.06118,0.04111,-0.00564,-0.05498,0.02334
calculated_host_listings_count,0.23667,-0.0,0.15754,0.42944,0.42944,0.07954,-0.06543,-0.11818,NaN,-0.05754,...,-0.00518,-0.00518,NaN,0.02989,0.12938,-0.05406,-0.08352,-0.01243,0.09949,0.04675
calculated_host_listings_count_entire_homes,0.13713,0.0,0.02524,0.54188,0.54188,0.07065,-0.12713,-0.01929,NaN,-0.00212,...,-0.00081,-0.00081,NaN,0.10168,0.01163,-0.04190,-0.14256,0.04999,0.01930,0.13010
calculated_host_listings_count_private_rooms,0.21188,-0.0,0.19320,0.14915,0.14915,0.05096,0.01401,-0.14499,NaN,-0.07591,...,-0.00634,-0.00634,NaN,-0.04168,0.16732,-0.03991,0.00213,-0.05728,0.11927,-0.04169
calculated_host_listings_count_shared_rooms,0.04671,-0.0,0.07831,-0.01595,-0.01595,0.00762,0.02066,-0.05161,NaN,-0.04902,...,-0.00335,-0.00335,NaN,-0.03324,0.01101,0.02082,-0.01928,-0.01131,0.01389,0.00810
reviews_per_month,0.23169,0.0,0.20844,-0.02096,-0.02096,-0.03667,0.07121,0.06850,NaN,0.03030,...,-0.00638,-0.00638,NaN,-0.00379,-0.00329,-0.04892,-0.20592,-0.04801,-0.02663,0.28524
label_price,0.07907,-0.0,0.04053,0.13104,0.13104,0.04330,-0.20695,0.50062,NaN,0.41996,...,0.04450,0.04450,NaN,0.02381,-0.03461,0.00792,-0.10279,0.01335,-0.02111,0.11721
host_listings_count_na,-0.00830,-0.0,-0.00371,-0.00000,-0.00000,0.00199,-0.01261,0.00519,NaN,-0.00089,...,1.00000,1.00000,NaN,-0.00728,-0.00772,-0.00620,0.03302,-0.00873,-0.01199,-0.01912
host_total_listings_count_na,-0.00830,-0.0,-0.00371,-0.00000,-0.00000,0.00199,-0.01261,0.00519,NaN,-0.00089,...,1.00000,1.00000,NaN,-0.00728,-0.00772,-0.00620,0.03302,-0.00873,-0.01199,-0.01912
bathrooms_na,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bedrooms_na,0.03343,0.0,0.03354,0.01297,0.01297,0.05533,-0.10992,-0.05957,NaN,-0.00000,...,-0.00728,-0.00728,NaN,1.00000,0.04985,-0.00898,-0.02418,0.02494,-0.00819,0.02186
beds_na,0.13640,-0.0,0.09218,-0.01032,-0.01032,0.02258,0.00221,-0.06916,NaN,-0.04571,...,-0.00772,-0.00772,NaN,0.04985,1.00000,0.04385,-0.02452,0.02050,0.00105,-0.00536
host_response_time_a few days or more,0.01215,0.0,0.04055,-0.03124,-0.03124,0.02052,-0.01400,0.01101,NaN,0.01969,...,-0.00620,-0.00620,NaN,-0.00898,0.04385,1.00000,-0.18787,-0.06088,-0.08364,-0.13339
host_response_time_unavailable,-0.35410,-0.0,-0.24094,-0.11686,-0.11686,0.01134,-0.07471,-0.11168,NaN,-0.09343,...,0.03302,0.03302,NaN,-0.02418,-0.02452,-0.18787,1.00000,-0.26424,-0.36305,-0.57898
host_response_time_within a day,-0.01164,-0.0,-0.05562,-0.03119,-0.03119,0.01410,-0.03805,0.01642,NaN,0.03512,...,-0.00873,-0.00873,NaN,0.02494,0.02050,-0.06088,-0.26424,1.00000,-0.11764,-0.18761
host_response_time_within a few hours,0.12780,-0.0,0.01844,-0.01468,-0.01468,-0.00499,0.03534,-0.00382,NaN,0.01114,...,-0.01199,-0.01199,NaN,-0.00819,0.00105,-0.08364,-0.36305,-0.11764,1.00000,-0.25777
host_response_time_within an hour,0.29187,-0.0,0.26491,0.17132,0.17132,-0.02598,0.08358,0.11060,NaN,0.06432,...,-0.01912,-0.01912,NaN,0.02186,-0.00536,-0.13339,-0.57898,-0.18761,-0.25777,1.00000

The result is a computed *correlation matrix*. The values on the diagonal are all equal to 1 because they represent the correlations between each column with itself. The matrix is symmetrical with respect to the diagonal.<br>

We only need to observe correlations of all features with the column `label_price` (as opposed to every possible pairwise correlation). Se let's query the `label_price` column of this matrix:

**Task**: Extract the `label_price` column of the correlation matrix and save the results to the variable `corrs`.

In [43]:
corrs = corr_matrix['label_price']
corrs

id                                              0.07907
scrape_id                                      -0.00000
host_id                                         0.04053
host_listings_count                             0.13104
host_total_listings_count                       0.13104
latitude                                        0.04330
longitude                                      -0.20695
accommodates                                    0.50062
bathrooms                                           NaN
bedrooms                                        0.41996
beds                                            0.37370
price                                           0.71112
minimum_nights                                 -0.07589
maximum_nights                                 -0.00097
minimum_minimum_nights                         -0.03804
maximum_minimum_nights                          0.06554
minimum_maximum_nights                          0.06582
maximum_maximum_nights                          0.11169
minimum_nights_avg_ntm                          0.06388
maximum_nights_avg_ntm                          0.08210
calendar_updated                                    NaN
availability_30                                 0.14569
availability_60                                 0.14701
availability_90                                 0.14391
availability_365                                0.12356
number_of_reviews                              -0.04197
number_of_reviews_ltm                           0.02757
number_of_reviews_l30d                          0.02159
review_scores_rating                            0.04320
review_scores_accuracy                          0.00536
review_scores_cleanliness                       0.08254
review_scores_checkin                          -0.00367
review_scores_communication                     0.00012
review_scores_location                          0.09724
review_scores_value                            -0.00482
calculated_host_listings_count                 -0.01582
calculated_host_listings_count_entire_homes     0.09509
calculated_host_listings_count_private_rooms   -0.09978
calculated_host_listings_count_shared_rooms    -0.04334
reviews_per_month                               0.03114
label_price                                     1.00000
host_listings_count_na                          0.04450
host_total_listings_count_na                    0.04450
bathrooms_na                                        NaN
bedrooms_na                                     0.02381
beds_na                                        -0.03461
host_response_time_a few days or more           0.00792
host_response_time_unavailable                 -0.10279
host_response_time_within a day                 0.01335
host_response_time_within a few hours          -0.02111
host_response_time_within an hour               0.11721
Name: label_price, dtype: float64

**Task**: Sort the values of the series we just obtained in the descending order and save the results to the variable `corrs_sorted`.

In [52]:
corrs_sorted = corrs.sort_values(ascending=False)
corrs_sorted

label_price                                     1.00000
price                                           0.71112
accommodates                                    0.50062
bedrooms                                        0.41996
beds                                            0.37370
availability_60                                 0.14701
availability_30                                 0.14569
availability_90                                 0.14391
host_listings_count                             0.13104
host_total_listings_count                       0.13104
availability_365                                0.12356
host_response_time_within an hour               0.11721
maximum_maximum_nights                          0.11169
review_scores_location                          0.09724
calculated_host_listings_count_entire_homes     0.09509
review_scores_cleanliness                       0.08254
maximum_nights_avg_ntm                          0.08210
id                                              0.07907
minimum_maximum_nights                          0.06582
maximum_minimum_nights                          0.06554
minimum_nights_avg_ntm                          0.06388
host_total_listings_count_na                    0.04450
host_listings_count_na                          0.04450
latitude                                        0.04330
review_scores_rating                            0.04320
host_id                                         0.04053
reviews_per_month                               0.03114
number_of_reviews_ltm                           0.02757
bedrooms_na                                     0.02381
number_of_reviews_l30d                          0.02159
host_response_time_within a day                 0.01335
host_response_time_a few days or more           0.00792
review_scores_accuracy                          0.00536
review_scores_communication                     0.00012
scrape_id                                      -0.00000
maximum_nights                                 -0.00097
review_scores_checkin                          -0.00367
review_scores_value                            -0.00482
calculated_host_listings_count                 -0.01582
host_response_time_within a few hours          -0.02111
beds_na                                        -0.03461
minimum_minimum_nights                         -0.03804
number_of_reviews                              -0.04197
calculated_host_listings_count_shared_rooms    -0.04334
minimum_nights                                 -0.07589
calculated_host_listings_count_private_rooms   -0.09978
host_response_time_unavailable                 -0.10279
longitude                                      -0.20695
bathrooms                                           NaN
calendar_updated                                    NaN
bathrooms_na                                        NaN
Name: label_price, dtype: float64

**Task**: Use Pandas indexing to extract the column names for the top two correlation values and save the results to the Python list `top_two_corr`. Add the feature names to the list in the order in which they appear in the output above. <br> 

<b>Note</b>: Do not count the correlation of `label` column with itself, nor the `price` column -- which is the `label` column prior to outlier removal.

In [56]:
top_two_corr = corrs_sorted.iloc[1:3].index.tolist()
top_two_corr

['price', 'accommodates']

#### Bivariate Plotting: Produce Plots for the Label and Its Top Correlates

Let us visualize our data.

We will use the `pairplot()` function in `seaborn` to plot the relationships between the two features and the label.

**Task**: Create a DataFrame `df_corrs` that contains only three columns from DataFrame `df`: the label, and the two columns which correlate with it the most.

In [57]:
df_corrs = df[['label_price'] + top_two_corr]
df_corrs

       label_price  price  accommodates
0            150.0  150.0             1
1             75.0   75.0             3
2             60.0   60.0             2
3            275.0  275.0             4
4             68.0   68.0             2
...            ...    ...           ...
38272         79.0   79.0             2
38273         76.0   76.0             2
38274        116.0  116.0             2
38275        106.0  106.0             2
38276        689.0  689.0            14

[38277 rows x 3 columns]

**Task**: Create a `seaborn` pairplot of the data subset you just created. Specify the *kernel density estimator* as the kind of the plot, and make sure that you don't plot redundant plots.

<i>Note</i>: It will take a few minutes to run and produce a plot.

In [ ]:
sns.pairplot(df_corrs, kind='kde')
plt.show()

## Part 5: Analysis

1. Think about the possible interpretation of the plot. Recall that the label is the listing price. <br> How would you explain the relationship between the label and the two features? Is there a slight tilt to the points cluster, as the price goes up?<br>
2. Are the top two correlated features strongly or weakly correlated with the label? Are they features that should be used for our predictive machine learning problem?
3. Inspect your data matrix. It has a few features that contain unstructured text, meaning text data that is neither numerical nor categorical. List some features that contain unstructured text that you think are valuable for our predictive machine learning problem. Are there other remaining features that you think need to be prepared for the modeling phase? Do you have any suggestions on how to prepare these features?

Record your findings in the cell below.

<Double click this Markdown cell to make it editable, and record your findings here.>